const { Product, sequelize } = require("../models");

module.exports = async () => {
  await Product.destroy({ where: {} });

  await sequelize.query("ALTER TABLE products AUTO_INCREMENT = 1");

  const products = [
    {
      id: 31,
      name: "Camperita Impermeable Azul",
      description: "Con capucha y cierre. Repele el agua.",
      image: "https://mascotasmimadas.com.uy/wp-content/uploads/2024/06/IM-ROPA-4104-portada.png",
      price: 950,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 32,
      name: "Sweater de Lana Rojo",
      description: "Calentito y hecho a mano.",
      image: "https://www.tusmascotas.cl/wp-content/uploads/2022/04/chaleco-rojo-.png",
      price: 1100,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 33,
      name: "Remera Veraniega Rayada",
      description: "Tela liviana, fresca para verano.",
      image:
        "https://www.colettetgaston.com/cdn/shop/files/high_quality_dog_shirt.png?v=1749159105&width=533",
      price: 750,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 34,
      name: "Disfraz de Abejita",
      description: "Con alas y antenas, adorable para fotos.",
      image: "https://greenpets.com.co/wp-content/uploads/2021/10/abeja-green-pets.png",
      price: 1200,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 35,
      name: "Botitas Antideslizantes",
      description: "Para el pavimento caliente o húmedo.",
      image: "https://per-ros.com/productos/botitas%20(1)-27.png",
      price: 890,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 36,
      name: "Capa Batman para Perros",
      description: "Disfraz con velcro, súper héroe peludo.",
      image: "https://img.chilango.com/2019/10/Captura-de-Pantalla-2019-10-29-a-las-18.34.26.png",
      price: 1300,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 37,
      name: "Pañuelo Estilo Cowboy",
      description: "Accesorio cómodo y estiloso.",
      image:
        "https://png.pngtree.com/png-clipart/20250109/original/pngtree-cowboy-bandana-isolated-white-backdrop-png-image_18970791.png",
      price: 390,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 38,
      name: "Chaleco de Polar Gris",
      description: "Abriga sin molestar el movimiento.",
      image: "https://nuevaerauruguay.com/wp-content/uploads/2025/04/Dog-Jacket-16.png",
      price: 980,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 39,
      name: "Camiseta Messi para Mascotas",
      description: "¡Para los fanas del fútbol!",
      image:
        "https://acdn-us.mitiendanube.com/stores/035/032/products/remera-argentina1-04b04f33c2f1fb6e6816691505601044-640-0.png",
      price: 1400,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 40,
      name: "Capa de Lluvia Transparente",
      description: "Se ajusta fácil, protege del agua.",
      image: "https://http2.mlstatic.com/D_NQ_NP_648127-MLU84103751139_042025-O.webp",
      price: 890,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 41,
      name: "Jardinerito de Jean",
      description: "Ropa de paseo con estilo canchero.",
      image: "https://http2.mlstatic.com/D_NQ_NP_692935-MLU73066826549_112023-O.webp",
      price: 1250,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 42,
      name: "Bufanda de Tejido Suave",
      description: "Complemento ideal para invierno.",
      image: "https://m.media-amazon.com/images/I/61PZblIY9xL._AC_UF894,1000_QL80_.jpg",
      price: 520,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 43,
      name: "Vestido Floral",
      description: "Para perritas con onda veraniega.",
      image: "https://m.media-amazon.com/images/I/71HSgl9eZlL.jpg",
      price: 970,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 44,
      name: "Pijama para Mascotas",
      description: "Suave, ideal para dormir calentitos.",
      image: "https://http2.mlstatic.com/D_NQ_NP_941420-MLU51024289085_082022-O.webp",
      price: 1140,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 45,
      name: "Buzo de Unicornio",
      description: "Con capucha con cuernito incluido.",
      image: "https://m.media-amazon.com/images/I/61XhSQaLV2L.jpg",
      price: 1320,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 46,
      name: "Conjunto Deportivo Mini",
      description: "Para look casual y cómodo.",
      image: "https://i.pinimg.com/736x/bd/d8/cd/bdd8cd9a868f5b6aba8f319d9bacc92d.jpg",
      price: 990,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 47,
      name: "Gorro de Lluvia",
      description: "Protege la cabecita del agua.",
      image:
        "https://frenchiemania.com/wp-content/uploads/2022/04/como-proteger-perro-lluvia-gorros-impermeables-para-perros-2.jpg",
      price: 430,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 48,
      name: "Kimono para Mascotas",
      description: "Estilo oriental con tela liviana.",
      image: "https://m.media-amazon.com/images/I/71nOKambE3L._AC_UF894,1000_QL80_.jpg",
      price: 1500,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 49,
      name: "Disfraz de Dinosaurio",
      description: "Con cresta y cola, ¡súper divertido!",
      image: "https://m.media-amazon.com/images/I/71SrAD1aCYL._AC_UF1000,1000_QL80_.jpg",
      price: 1380,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 50,
      name: "Parka Reversible",
      description: "Dos estilos en uno, resistente y abrigada.",
      image:
        "https://cdnx.jumpseller.com/alo-mascotas/image/25122293/e2176496840fb9f9071cc08f1c119315.jpg?1658115894",
      price: 1650,
      stock: 25,
      category: "ropa",
      featured: true,
    },
    {
      id: 51,
      name: "Pelota de Goma con Sonido",
      description: "Mordible y sonora, ideal para jugar.",
      image:
        "https://png.pngtree.com/png-vector/20230915/ourmid/pngtree-red-inflatable-rubber-ball-inflatable-png-image_9244542.png",
      price: 430,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 52,
      name: "Cuerda con Nudos",
      description: "Fuerte, perfecta para tirar y morder.",
      image:
        "https://www.americanpet.com.uy/images/virtuemart/product/resized/IMG_0679_640x640.png",
      price: 390,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 53,
      name: "Huesito de Plástico Duro",
      description: "Duradero y alivia el estrés.",
      image:
        "https://pet-health-content-media.chewy.com/wp-content/uploads/2025/04/16213146/202504bec-Orbbe-tuff-dog-toy.png",
      price: 460,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 54,
      name: "Peluchito con Chillido",
      description: "Suave y chillón, ideal para cachorros.",
      image:
        "https://png.pngtree.com/png-vector/20250321/ourmid/pngtree-squeaky-toys-isolated-on-a-transparent-background-png-image_15807162.png",
      price: 510,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 55,
      name: "Disco Volador para Perros",
      description: "Flexible, divertido para correr.",
      image: "https://pngimg.com/d/frisbee_PNG6.png",
      price: 580,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 56,
      name: "Kong Clásico Rojo",
      description: "Rellenable con premios, súper resistente.",
      image:
        "https://www.petland.ca/cdn/shop/files/kong-kong-classic-dog-toy-29509678170214.png?v=1691378832",
      price: 1650,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 57,
      name: "Pelota Dental",
      description: "Con textura que limpia los dientes.",
      image:
        "https://www.woowguau.mx/cdn/shop/products/4680_Imagen1__52967_zoom_512x512.png?v=1602537723",
      price: 690,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 58,
      name: "Ratita de Tela",
      description: "Para perros pequeños o Gatitos, liviana y chillona.",
      image:
        "https://png.pngtree.com/png-vector/20240807/ourmid/pngtree-more-less-or-equal-with-cute-pet-toys-png-image_13149917.png",
      price: 350,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 59,
      name: "Túnel de Juego",
      description: "Para perros pequeños y medianos.",
      image:
        "https://png.pngtree.com/png-clipart/20250424/original/pngtree-a-pet-toy-tunnel-with-fabric-design-care-product-png-image_20779555.png",
      price: 1950,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 60,
      name: "Mordillo Helado",
      description: "Ideal para aliviar encías en cachorros.",
      image:
        "https://s3-sa-east-1.amazonaws.com/mispichos.com.ar/mp_images/desktop_can-cat-paleta-mordillo-ice_935",
      price: 720,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 61,
      name: "Zanahoria de Felpa",
      description: "Diseño simpático con sonido interno.",
      image:
        "https://png.pngtree.com/png-clipart/20220927/original/pngtree-3dc4d-three-dimensional-plush-fruits-and-vegetables-carrots-png-image_8637568.png",
      price: 540,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 62,
      name: "Anillo de Goma Fuerte",
      description: "Para juegos de tracción con humanos.",
      image: "https://petslovers.es/1114-thickbox_default/barry-king-anillo-de-goma-macizo.jpg",
      price: 630,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 63,
      name: "Set de Pelotas Pequeñas",
      description: "Paquete con 3 mini pelotas resistentes.",
      image:
        "https://png.pngtree.com/png-vector/20240317/ourmid/pngtree-colorful-toy-balls-png-image_11989170.png",
      price: 870,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 64,
      name: "Juguete Interactivo Dispensador",
      description: "Suelta premios al girar.",
      image:
        "https://inventario-petuniverse.s3.amazonaws.com/product_pics/numbell_dispensador_bolsa_celeste_sin_fondo.png",
      price: 480,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 65,
      name: "Conejito de Cuerda",
      description: "Textura y forma divertida para jugar.",
      image:
        "https://png.pngtree.com/png-clipart/20240227/original/pngtree-wind-up-vintage-toy-rabbit-material-photo-png-image_14427971.png",
      price: 430,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 66,
      name: "Juguete en Forma de Donut",
      description: "Mordible y con aroma a vainilla.",
      image:
        "https://static.vecteezy.com/system/resources/previews/015/310/780/non_2x/donut-stacking-toy-with-transparent-background-png.png",
      price: 500,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 67,
      name: "Pez Mordedor",
      description: "Juguete con aletas móviles y chillón.",
      image:
        "https://png.pngtree.com/png-clipart/20231213/original/pngtree-fish-toy-character-of-finding-nemo-black-photo-png-image_13833691.png",
      price: 580,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 68,
      name: "Pulpo de Tela con Patitas",
      description: "Con múltiples texturas y sonido.",
      image:
        "https://www.castaburdeos.com.mx/cdn/shop/files/juguete_forma_de_pulpo_para_mascota_3475.png?v=1699466811",
      price: 670,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 69,
      name: "Lanzador de Pelotas",
      description: "Incluye pelota. Perfecto para exteriores.",
      image: "https://fancypets.mx/IMAGENES/FANCY%20PETS/1000x1000_72_png/FL9422/FL9422_E.png",
      price: 880,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
    {
      id: 70,
      name: "Pelota LED con Movimiento",
      description: "Se mueve sola e ilumina. Estimula el juego.",
      image:
        "https://www.somoswapp.com.ar/media/catalog/product/cache/4e187a3216125186f353d1ef896e6af4/p/e/pelota_huella_led_combinada.png",
      price: 2100,
      stock: 25,
      category: "juguetes",
      featured: true,
    },
  ];

  await Product.bulkCreate(products);

  console.log("[Database] Seeder de Products ejecutado: productos eliminados y IDs reiniciados.");
};
