const { Product, sequelize } = require("../models");

module.exports = async () => {
  await Product.destroy({ where: {} });
  await sequelize.query("ALTER TABLE products AUTO_INCREMENT = 1");

  const products = [
    {
      name: "Camperita Impermeable Azul",
      description: "Con capucha y cierre. Repele el agua.",
      image: "https://mascotasmimadas.com.uy/wp-content/uploads/2024/06/IM-ROPA-4104-portada.png",
      price: 950,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Sweater de Lana Rojo",
      description: "Calentito y hecho a mano.",
      image: "https://www.tusmascotas.cl/wp-content/uploads/2022/04/chaleco-rojo-.png",
      price: 1100,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Remera Veraniega Rayada",
      description: "Tela liviana, fresca para verano.",
      image:
        "https://www.colettetgaston.com/cdn/shop/files/high_quality_dog_shirt.png?v=1749159105&width=533",
      price: 750,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Disfraz de Abejita",
      description: "Con alas y antenas, adorable para fotos.",
      image: "https://greenpets.com.co/wp-content/uploads/2021/10/abeja-green-pets.png",
      price: 1200,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Botitas Antideslizantes",
      description: "Para el pavimento caliente o húmedo.",
      image: "https://per-ros.com/productos/botitas%20(1)-27.png",
      price: 890,
      stock: 25,
      subcategoryId: 25,
      featured: true,
    },
    {
      name: "Capa Batman para Perros",
      description: "Disfraz con velcro, súper héroe peludo.",
      image: "https://img.chilango.com/2019/10/Captura-de-Pantalla-2019-10-29-a-las-18.34.26.png",
      price: 1300,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Pañuelo Estilo Cowboy",
      description: "Accesorio cómodo y estiloso.",
      image:
        "https://png.pngtree.com/png-clipart/20250109/original/pngtree-cowboy-bandana-isolated-white-backdrop-png-image_18970791.png",
      price: 390,
      stock: 25,
      subcategoryId: 27,
      featured: true,
    },
    {
      name: "Chaleco de Polar Gris",
      description: "Abriga sin molestar el movimiento.",
      image: "https://nuevaerauruguay.com/wp-content/uploads/2025/04/Dog-Jacket-16.png",
      price: 980,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Camiseta Messi para Mascotas",
      description: "¡Para los fanas del fútbol!",
      image:
        "https://acdn-us.mitiendanube.com/stores/035/032/products/remera-argentina1-04b04f33c2f1fb6e6816691505601044-640-0.png",
      price: 1400,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Capa de Lluvia Transparente",
      description: "Se ajusta fácil, protege del agua.",
      image: "https://http2.mlstatic.com/D_NQ_NP_648127-MLU84103751139_042025-O.webp",
      price: 890,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Jardinerito de Jean",
      description: "Ropa de paseo con estilo canchero.",
      image: "https://http2.mlstatic.com/D_NQ_NP_692935-MLU73066826549_112023-O.webp",
      price: 1250,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Bufanda de Tejido Suave",
      description: "Complemento ideal para invierno.",
      image: "https://m.media-amazon.com/images/I/61PZblIY9xL._AC_UF894,1000_QL80_.jpg",
      price: 520,
      stock: 25,
      subcategoryId: 27,
      featured: true,
    },
    {
      name: "Vestido Floral",
      description: "Para perritas con onda veraniega.",
      image: "https://m.media-amazon.com/images/I/71HSgl9eZlL.jpg",
      price: 970,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Pijama para Mascotas",
      description: "Suave, ideal para dormir calentitos.",
      image: "https://http2.mlstatic.com/D_NQ_NP_941420-MLU51024289085_082022-O.webp",
      price: 1140,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Buzo de Unicornio",
      description: "Con capucha con cuernito incluido.",
      image: "https://m.media-amazon.com/images/I/61XhSQaLV2L.jpg",
      price: 1320,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Conjunto Deportivo Mini",
      description: "Para look casual y cómodo.",
      image: "https://i.pinimg.com/736x/bd/d8/cd/bdd8cd9a868f5b6aba8f319d9bacc92d.jpg",
      price: 990,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Gorro de Lluvia",
      description: "Protege la cabecita del agua.",
      image:
        "https://frenchiemania.com/wp-content/uploads/2022/04/como-proteger-perro-lluvia-gorros-impermeables-para-perros-2.jpg",
      price: 430,
      stock: 25,
      subcategoryId: 27,
      featured: true,
    },
    {
      name: "Kimono para Mascotas",
      description: "Estilo oriental con tela liviana.",
      image: "https://m.media-amazon.com/images/I/71nOKambE3L._AC_UF894,1000_QL80_.jpg",
      price: 1500,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Disfraz de Dinosaurio",
      description: "Con cresta y cola, ¡súper divertido!",
      image: "https://m.media-amazon.com/images/I/71SrAD1aCYL._AC_UF1000,1000_QL80_.jpg",
      price: 1380,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
    {
      name: "Parka Reversible",
      description: "Dos estilos en uno, resistente y abrigada.",
      image:
        "https://cdnx.jumpseller.com/alo-mascotas/image/25122293/e2176496840fb9f9071cc08f1c119315.jpg?1658115894",
      price: 1650,
      stock: 25,
      subcategoryId: 26,
      featured: true,
    },
  ];
  await Product.bulkCreate(products);
  console.log("[Database] Seeder ejecutado: productos insertados.");
};
